name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Asegúrate de que aquí esté tu index.html

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
