name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Asegúrate que index.html y otros archivos estén aquí

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

